// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQtJ0h5CLY6mSbt4C9XGtuQBRI3oYeOto',
    appId: '1:329457254948:web:a4da51573b2a4bed274eb1',
    messagingSenderId: '329457254948',
    projectId: 'my-bloc-chat-app-5456a',
    authDomain: 'my-bloc-chat-app-5456a.firebaseapp.com',
    storageBucket: 'my-bloc-chat-app-5456a.appspot.com',
    measurementId: 'G-SYE4H70NLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu3jnOa3Mf0V-jMO6XCJNWCufFHAWv9jY',
    appId: '1:329457254948:android:a2b876475f6861a0274eb1',
    messagingSenderId: '329457254948',
    projectId: 'my-bloc-chat-app-5456a',
    storageBucket: 'my-bloc-chat-app-5456a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBTVczh_KhangP4_pL_fzW1v3q3bGOPxI',
    appId: '1:329457254948:ios:92136c61323404ed274eb1',
    messagingSenderId: '329457254948',
    projectId: 'my-bloc-chat-app-5456a',
    storageBucket: 'my-bloc-chat-app-5456a.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBTVczh_KhangP4_pL_fzW1v3q3bGOPxI',
    appId: '1:329457254948:ios:92136c61323404ed274eb1',
    messagingSenderId: '329457254948',
    projectId: 'my-bloc-chat-app-5456a',
    storageBucket: 'my-bloc-chat-app-5456a.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQtJ0h5CLY6mSbt4C9XGtuQBRI3oYeOto',
    appId: '1:329457254948:web:158aad093165a36b274eb1',
    messagingSenderId: '329457254948',
    projectId: 'my-bloc-chat-app-5456a',
    authDomain: 'my-bloc-chat-app-5456a.firebaseapp.com',
    storageBucket: 'my-bloc-chat-app-5456a.appspot.com',
    measurementId: 'G-VHC3NV29MJ',
  );
}
